package com.android.settings.other;

public enum EN_SLEEP_TIME_STATE {
	STATE_SLEEP_OFF,
	STATE_SLEEP_5MIN,
	STATE_SLEEP_10MIN,
	STATE_SLEEP_15MIN,
	STATE_SLEEP_30MIN,
	STATE_SLEEP_45MIN,
	STATE_SLEEP_60MIN,
	STATE_SLEEP_90MIN,
	STATE_SLEEP_120MIN,
	STATE_SLEEP_180MIN,
	STATE_SLEEP_240MIN
}
